grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: issuer
    hosts:
      - grafana.eks.madil.co.uk
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.eks.madil.co.uk

prometheus:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "issuer"
    hosts:
      - prometheus.eks.madil.co.uk
    tls:
      - hosts:
          - prometheus.eks.madil.co.uk
        secretName: prometheus-tls
